name: py_flask_application
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - flask
  - sqlalchemy
  - flask-sqlalchemy
  - flask-wtf
  - flask-migrate
  - pytest
  - pytest-flask
  - pip
  - pip:
    - flask-bootstrap